# Generated by Django 4.0.3 on 2022-03-07 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('device_id', models.CharField(blank=True, help_text='Enter the Device name', max_length=100)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitored_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('device_id', models.CharField(blank=True, help_text='Enter the Device name', max_length=100)),
                ('heart_rate', models.IntegerField(default='0000000', help_text='Enter the heart rate')),
                ('body_temperature', models.IntegerField(default='0000000', help_text='Enter the temperature')),
                ('humidity', models.IntegerField(default='0000000', help_text='Enter the temperature')),
                ('environment_temperature', models.IntegerField(default='0000000', help_text='Enter the temperature')),
                ('reading', models.TextField(default='0000', help_text='Enter the value')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthMonitorApp.profile')),
            ],
            options={
                'ordering': ['created', 'user_ID'],
            },
        ),
    ]
