# Generated by Django 4.0.3 on 2022-03-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitored_detail',
            name='blood_oxygen',
            field=models.IntegerField(default='0000000', help_text='Enter the oxygen'),
        ),
    ]
