# Generated by Django 4.0.3 on 2022-03-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitorApp', '0002_monitored_detail_blood_oxygen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitored_detail',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='monitored_detail',
            name='user_ID',
        ),
    ]
