# Generated by Django 4.0.3 on 2022-03-08 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitorApp', '0003_alter_monitored_detail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fall_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text='Enter the Device name', max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
